### ISSUE TITLE
Suspend org

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-backend#5]
Summary: There is currently no way to archive or suspend an org. We don't want to lose data, but may need to stop someone's access. On the edit screen, can we add a suspend button? To make things a bit safer, maybe there is an email with a link sent to super admin, and they have to click the link to accept and allow the suspension? open to ideas here.

**Comment by bartmika** [comment]
@rodolfomartinez Backend supports it but we'll need to update frontend GUI to support this feature. Labelled this as an `enhancement`.
